
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEANO COMA ENTERO HILERA IDENTIFICADOR L_CORCHETE L_CUADRADO L_PARENTESIS OPERADOR OPERADOR_LOGICO PALABRA_CLAVE PUNTO PUNTO_Y_COMA R_CORCHETE R_CUADRADO R_PARENTESIS\n   inicial : programa\n   \n   programa : claseprincipal declclase\n   \n   claseprincipal : IDENTIFICADOR\n   \n    declclase : PALABRA_CLAVE\n    \n    empty :\n    '
    
_lr_action_items = {'IDENTIFICADOR':([0,],[4,]),'$end':([1,2,5,6,],[0,-1,-2,-4,]),'PALABRA_CLAVE':([3,4,],[6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicial':([0,],[1,]),'programa':([0,],[2,]),'claseprincipal':([0,],[3,]),'declclase':([3,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicial","S'",1,None,None,None),
  ('inicial -> programa','inicial',1,'p_inicial','plyExample.py',112),
  ('programa -> claseprincipal declclase','programa',2,'p_programa','plyExample.py',118),
  ('claseprincipal -> IDENTIFICADOR','claseprincipal',1,'p_claseprincipal','plyExample.py',124),
  ('declclase -> PALABRA_CLAVE','declclase',1,'p_declclase','plyExample.py',130),
  ('empty -> <empty>','empty',0,'p_empty','plyExample.py',136),
]
